---
classes:
  - '::fuel_project::jenkins::slave'
  - '::sudo'

fuel_project::jenkins::slave::verify_network_checker: true

# keep current sudo configuration
sudo::purge: false
sudo::config_file_replace: false

# https://bugs.launchpad.net/fuel/+bug/1458842
sudo::configs:
  'tcpdump':
    'content': '%sudo ALL=(ALL) NOPASSWD: /usr/sbin/tcpdump'
