---
classes:
  - '::fuel_project::roles::mailman'
apache::default_confd_files: false
apache::default_mods: false
fuel_project::roles::mailman::apache_aliases:
  - alias: /pipermail/
    path: /var/lib/mailman/archives/public/
  - alias: /images/mailman/
    path: /usr/share/images/mailman/
  - scriptalias: /cgi-bin/mailman/
    path: /usr/lib/cgi-bin/mailman/
  - scriptalias: /admin
    path: /usr/lib/cgi-bin/mailman/admin
  - scriptalias: /admindb
    path: /usr/lib/cgi-bin/mailman/admindb
  - scriptalias: /confirm
    path: /usr/lib/cgi-bin/mailman/confirm
  - scriptalias: /create
    path: /usr/lib/cgi-bin/mailman/create
  - scriptalias: /edithtml
    path: /usr/lib/cgi-bin/mailman/edithtml
  - scriptalias: /listinfo
    path: /usr/lib/cgi-bin/mailman/listinfo
  - scriptalias: /options
    path: /usr/lib/cgi-bin/mailman/options
  - scriptalias: /private
    path: /usr/lib/cgi-bin/mailman/private
  - scriptalias: /rmlist
    path: /usr/lib/cgi-bin/mailman/rmlist
  - scriptalias: /roster
    path: /usr/lib/cgi-bin/mailman/roster
  - scriptalias: /subscribe
    path: /usr/lib/cgi-bin/mailman/subscribe
fuel_project::roles::mailman::apache_directories:
  - path: /usr/lib/cgi-bin/mailman/
    allowoverride: false
    options: ExecCGI
    addhandlers:
      - handler: cgi-script
        extensions: .cgi
  - path: /var/lib/mailman/archives/public/
    options: FollowSymlinks
    allowoverride: false
  - path: /usr/share/images/mailman/
    allowoverride: false
  - path: /var/lib/mailman/archives/
    options: FollowSymlinks
    allowoverride: false
mailman::default_url_host: 'lists.example.com'
mailman::default_email_host: 'example.com'
mailman::mailman_site_list: 'mailman-list'
mailman::mm_cfg_settings:
  ALLOW_SITE_ADMIN_COOKIES: 'Yes'
  PUBLIC_ARCHIVE_URL: "'https://%(hostname)s/pipermail/%(listname)s'"
  MTA: "'Postfix'"
  POSTFIX_STYLE_VIRTUAL_DOMAINS: "'False'"
  DEFAULT_SUBJECT_PREFIX: "''"
  DEFAULT_REPLY_GOES_TO_LIST: '0'
  DEFAULT_URL_PATTERN: "'http://%s/cgi-bin/mailman/'"
