---
classes:
  - '::fuel_project::common'
  - '::mongodb::server'
  - '::mongodb::client'
fuel_project::apps::mongo::server::replication_members:
  - mongo01.local
  - mongo02.local
  - mongo03.local
mongodb::server::noauth: true
mongodb::server::port: 27017
mongodb::server::verbose: true
mongodb::server::replset: 'mongodb-misc'
