---
classes:
  - '::fuel_project::roles::zabbix::server'
  - '::bacula'
fuel_project::roles::zabbix::server::server_role: slave
# firewall configuration
fuel_project::apps::firewall::rules:
  '1000 - allow ssh connections from 0.0.0.0/0':
    source: 0.0.0.0/0
    dport: 22
    proto: tcp
    action: accept
  '1000 - allow bacula connections from 172.18.0.0/16':
    source: 172.18.0.0/16
    dport: 9102
    proto: tcp
    action: accept
  '1000 - allow zabbix-agent connections from 172.18.0.0/16':
    source: 172.18.0.0/16
    dport: 10050
    proto: tcp
    action: accept
